HastaneRandevuSistemi/Areas/Admin/Controllers/ClinicsController.cs
using Hastane.Models;
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace HastaneRandevuSistemi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ClinicsController : Controller
    {
        private IClinicService _clinic;
        public ClinicsController(IClinicService clinic)
        {
            _clinic = clinic;
        }
        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {
            return View(_clinic.GetAll(pageNumber, pageSize));
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _clinic.GetClinicById(id);
            return View(viewModel);
        }
        
        [HttpPost]
        public IActionResult Edit(ClinicViewModel vm)
        {
            _clinic.UpdateClinic(vm);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(ClinicViewModel vm)
        {
            _clinic.InsertClinic(vm);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _clinic.DeleteClinic(id);
            return RedirectToAction("Index");
        }
    }
}

HastaneRandevuSistemi/Areas/Admin/Controllers/DoktorController.cs
using Hastane.Models;
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace HastaneRandevuSistemi.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Hasta")]
    public class DoktorController : Controller
    {
        private IDoctorService _doctorService;
        public DoktorController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }
        [Authorize(Roles = "Admin, Hasta")]
        public IActionResult AllDoctors(int pageNumber = 1, int pageSize = 10)
        {
            return View(_doctorService.GetAllDoctor(pageNumber, pageSize));

        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _doctorService.GetDoctorById(id);
            return View(viewModel);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(DoctorViewModel vm)
        {
            _doctorService.UpdateDoctor(vm);
            return RedirectToAction("AllDoctors");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(DoctorViewModel vm)
        {
            _doctorService.InsertDoctor(vm);
            return RedirectToAction("AllDoctors");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _doctorService.DeleteDoctor(id);
            return RedirectToAction("AllDoctors");

        }

    }
}

HastaneRandevuSistemi/Areas/Admin/Controllers/RandevuController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Hastane.Controllers
{
    public class RandevuController : Controller
    {
        private readonly IRandevuService _randevuService;

        public RandevuController(IRandevuService randevuService)
        {
            _randevuService = randevuService;
        }

        public IActionResult RandevuAl()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RandevuAl(RandevuViewModel randevuViewModel)
        {
            if (ModelState.IsValid)
            {
                bool randevuAlindi = _randevuService.RandevuAl(
                    randevuViewModel.HastaEmail,
                    randevuViewModel.RandevuTarih,
                    randevuViewModel.DoctorId,
                    randevuViewModel.Description
                );

                if (randevuAlindi)
                {
                    return RedirectToAction("Randevularim");
                }

                ModelState.AddModelError("", "Randevu alınamadı. Lütfen tekrar deneyin.");
            }

            return View(randevuViewModel);
        }

        public IActionResult RandevuIptal(int randevuId)
        {
            // RandevuId'ye göre randevu bilgilerini getir
            var randevu = _randevuService.GetRandevuById(randevuId);

            if (randevu == null)
            {
                return NotFound();
            }

            var randevuViewModel = new RandevuViewModel
            {
                Id = randevu.Id,
                HastaEmail = randevu.HastaEmail,
                RandevuTarih = randevu.RandevuTarih,
                DoctorId = randevu.DoctorId,
                Description = randevu.Description
            };

            return View(randevuViewModel);
        }

        [HttpPost]
        public IActionResult RandevuIptalConfirmed(int id)
        {
            bool randevuIptalEdildi = _randevuService.RandevuIptal(id);

            if (randevuIptalEdildi)
            {
                return RedirectToAction("Randevularim", new { hastaMail = "hastaIdBurayaEklenecek" });
            }

            return View();
        }

        public IActionResult Randevularim()
        {
            // Kullanıcı oturum açmış mı kontrol et
            if (User.Identity.IsAuthenticated)
            {
                // Admin rolüne sahip kullanıcılar tüm randevuları görebilir
                if (User.IsInRole("Admin"))
                {
                    var randevular = _randevuService.GetAllRandevular();

                    var randevuViewModels = randevular.Select(r => new RandevuViewModel
                    {
                        Id = r.Id,
                        HastaEmail = r.HastaEmail,
                        RandevuTarih = r.RandevuTarih,
                        DoctorId = r.DoctorId,
                        Description = r.Description
                    }).ToList();

                    return View(randevuViewModels);
                }
                else
                {
                    string hastaMail = User.Identity.Name;

                    var randevular = _randevuService.GetRandevularByHastaId(hastaMail);

                    var randevuViewModels = randevular.Select(r => new RandevuViewModel
                    {
                        Id = r.Id,
                        HastaEmail = r.HastaEmail,
                        RandevuTarih = r.RandevuTarih,
                        DoctorId = r.DoctorId,
                        Description = r.Description
                    }).ToList();

                    return View(randevuViewModels);
                }
            }
            return RedirectToAction("Login");
        }
    }
}

HastaneRandevuSistemi/Areas/Admin/Controllers/UsersController.cs
using Hastane.Models;
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HastaneRandevuSistemi.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class UsersController : Controller
    {
        private IApplicationUserService _userService;

        public UsersController(IApplicationUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index(int pageNumber=1, int pageSize=10)
        {
            return View(_userService.GetAll(pageNumber,pageSize));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _userService.GetUserById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(ApplicationUserViewModel vm)
        {
            _userService.UpdateUser(vm);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction("Index");
        }

    }
}

HastaneRandevuSistemi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HastaneRandevuSistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HastaneRandevuSistemi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="light">
            <div class="container-fluid">
                <div class="navbar-brand">Hastane Randevu Sistemi</div>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Departments" asp-action="Index">Ana Bilim Dalları</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Clinics" asp-action="Index">Klinikler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Users" asp-action="Index">Hasta Listesi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="api" asp-action="DoktorApi">Doktor Api</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Hasta"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Doktor" asp-action="AllDoctors">Doktor Listesi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Randevu" asp-action="Randevularim">Randevular</a>
                            </li>
                        }
                    </ul>
                    <partial name = "_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Hastane Randevu Sistemi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Gizlilik</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>