HastaneRandevuSistemi/Areas/Admin/Controllers/DoktorController.cs
using Hastane.Models;
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace HastaneRandevuSistemi.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Hasta")]
    public class DoktorController : Controller
    {
        private IDoctorService _doctorService;
        public DoktorController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }
        [Authorize(Roles = "Admin, Hasta")]
        public IActionResult AllDoctors(int pageNumber = 1, int pageSize = 10)
        {
            return View(_doctorService.GetAllDoctor(pageNumber, pageSize));

        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _doctorService.GetDoctorById(id);
            return View(viewModel);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(DoctorViewModel vm)
        {
            _doctorService.UpdateDoctor(vm);
            return RedirectToAction("AllDoctors");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(DoctorViewModel vm)
        {
            _doctorService.InsertDoctor(vm);
            return RedirectToAction("AllDoctors");
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _doctorService.DeleteDoctor(id);
            return RedirectToAction("AllDoctors");

        }

    }
}

HastaneRandevuSistemi/Areas/Admin/Controllers/DoktorUserController.cs
using Hastane.Services;
using Hastane.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HastaneRandevuSistemi.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DoktorUserController : Controller
    {
        private IDoctorService _doctorService;
        public DoktorUserController(IDoctorService doctorService)
        {
            _doctorService = doctorService;
        }
        public IActionResult AllDoctors(int pageNumber = 1, int pageSize = 10)
        {
            return View(_doctorService.GetAllDoctor(pageNumber, pageSize));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _doctorService.GetDoctorById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(DoctorViewModel vm)
        {
            _doctorService.UpdateDoctor(vm);
            return RedirectToAction("AllDoctors");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DoctorViewModel vm)
        {
            _doctorService.InsertDoctor(vm);
            return RedirectToAction("AllDoctors");
        }
        public IActionResult Delete(int id)
        {
            _doctorService.DeleteDoctor(id);
            return RedirectToAction("AllDoctors");

        }

    }
}

HastaneRandevuSistemi/Areas/Admin/Views/Doktor/AllDoctors.cshtml
@using Hastane.Utilities;
@model PagedResult<Hastane.ViewModels.DoctorViewModel>

@{
    ViewData["Title"] = "AllDoctors";
}

<br>
<br>
<h2>Doktor Listesi</h2>
<br>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">İsim</th>
            @if (User.IsInRole("Admin"))
            {
                <th scope="col">Email</th>
            }
            <th scope="col">Cinsiyet</th>
            @if (User.IsInRole("Admin"))
            {
                <th scope="col">Doğum Tarihi</th>
            }
            <th scope="col">Uzmanlık</th>
            <th scope="col">Poliklinik No</th>
            @if (User.IsInRole("Admin"))
            {
                <th scope="col">İşlem</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr class="table-@((item.Id % 2 == 0) ? "danger" : "active")">
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Specialist)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clinic.Number)
                </td>
                @if (User.IsInRole("Admin"))
                {
                    <td>
                        <a href="@Url.Action("Edit", new { id=item.Id })" class="btn btn-primary btn-sm" role="button">Düzenle</a>
                    <a href="@Url.Action("Delete", new { id=item.Id })" class="btn btn-primary btn-sm" role="button">Sil</a>
                </td>
                }
            </tr>
        }
    </tbody>
</table>
@if (User.IsInRole("Admin"))
{
    <p>
        <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Create")'">Yeni Oluştur</button>
    </p>
}
<cs-pager cs-paging-pagesize=(int)Model.PageSize
          cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-pagenumber-param="pageNumber"
          asp-controller="DoktorUser"
          asp-action="AllDoctors"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">
</cs-pager>

HastaneRandevuSistemi/Areas/Admin/Views/Doktor/Create.cshtml
@using Hastane.Models;
@model Hastane.ViewModels.DoctorViewModel

@{
    ViewData["Title"] = "Create";
}

<br>
<br>
<h2>Doktor Ekle</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="UserId" class="form-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Gender" class="form-label"></label>
                <select asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()" class="form-control">
                    <option value="">Seçiniz</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Address" class="form-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="DateOfBirth" class="form-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>

            <div class="mb-3 form-check">
                <input class="form-check-input" asp-for="IsDoctor" />
                <label class="form-check-label">
                    @Html.DisplayNameFor(model => model.IsDoctor)
                </label>
            </div>

            <div class="mb-3">
                <label asp-for="Specialist" class="form-label"></label>
                <input asp-for="Specialist" class="form-control" />
                <span asp-validation-for="Specialist" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="ClinicInfo" class="form-label"></label>
                <input asp-for="ClinicInfo" class="form-control" />
                <span asp-validation-for="ClinicInfo" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary me-3">Ekle</button>
                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("AllDoctors")'">Listeye Dön</button>
            </div>
        </form>
    </div>
</div>

HastaneRandevuSistemi/Areas/Admin/Views/Doktor/Edit.cshtml
@model Hastane.ViewModels.DoctorViewModel

@{
    ViewData["Title"] = "Edit";
}

<br>
<br>
<h2>Düzenle</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="Id" class="form-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="UserId" class="form-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Gender" class="form-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Address" class="form-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="DateOfBirth" class="form-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>

            <div class="mb-3 form-check">
                <input class="form-check-input" asp-for="IsDoctor" />
                <label class="form-check-label">
                    @Html.DisplayNameFor(model => model.IsDoctor)
                </label>
            </div>

            <div class="mb-3">
                <label asp-for="Specialist" class="form-label"></label>
                <input asp-for="Specialist" class="form-control" />
                <span asp-validation-for="Specialist" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="ClinicInfo" class="form-label"></label>
                <input asp-for="ClinicInfo" class="form-control" />
                <span asp-validation-for="ClinicInfo" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Kaydet</button>
                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index")'">Listeye Dön</button>
            </div>
        </form>
    </div>
</div>